use_frameworks!

target 'ShadowSocks-libev-iOS_Example' do
  pod 'ShadowSocks-libev-iOS', :path => '../'

  target 'ShadowSocks-libev-iOS_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
